# Generated by Django 4.1.7 on 2023-04-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_created=True)),
                ("content", models.CharField(max_length=255)),
                ("deadline", models.DateTimeField(blank=True)),
                ("complete", models.BooleanField()),
                (
                    "tags",
                    models.ManyToManyField(related_name="tasks", to="todo_list.tag"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.ManyToManyField(to="todo_list.task"),
        ),
    ]
