# Generated by Django 4.1.7 on 2023-04-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_list", "0002_alter_task_datetime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["complete", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="datetime",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="task",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
