# Generated by Django 4.1.7 on 2023-04-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "todo_list",
            "0003_alter_task_options_rename_datetime_task_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="name",
        ),
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(default=1, max_length=63),
            preserve_default=False,
        ),
    ]
